language: java
sudo: false

jdk:
- oraclejdk8

env:
  global:
  - secure: Y5WwLvftJ/7KdL/MYBPuPHwzgrKbAn8QNBXCAKiZUvw80sHtrrjrCgD68UVfikl/m1v/EBnBOkMg8b38ZCPo0YON4E2jIRjOl58GH0NQ5fS58Cp6LPNMmjlSJTEtEpJak7P7ADxwWFXm4AVKeYS04mF2TbwasVs4nMYddCv8QYY=
  - secure: lCc5UYBY5j3UYCPWfLGFj8NaMkiPyIGHKL6XfIFIW/pq6f7NN4xITSgR78iDiPawo+7SVMkxUHWM7MUimGTaAieAHSBzY+DdqlmPp5JvBWIw9RWou7Z3parRRQzUsTC65s+clr4VWa97nR5eNtb5FEvKvqCYZa2G0jjR9LabGYQ=

before_deploy:
- git config user.email "jason@vonnieda.org"
- git config --global user.name "Jason von Nieda"
- git clone --quiet --branch=gh-pages https://${GH_PAGES_TOKEN}@github.com/openpnp/openpnp gh-pages
- cd gh-pages
- mkdir -p $TRAVIS_BRANCH
- git rm -rf $TRAVIS_BRANCH
- javadoc -sourcepath ../src/main/java -subpackages org.openpnp -d $TRAVIS_BRANCH
- git add -f .
- git commit -m "Lastest javadoc on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to gh-pages"
- git push -fq origin gh-pages
- wget https://s3-us-west-2.amazonaws.com/openpnp/install4j_unix_6_0_4.tar.gz
- tar -xzf install4j_unix_6_0_4.tar.gz
- ./install4j6/bin/install4jc -L $INSTALL4J_LICENSE_KEY
- mvn package
- wget https://s3-us-west-2.amazonaws.com/openpnp/macosx-amd64-1.8.0_66.tar.gz
- wget https://s3-us-west-2.amazonaws.com/openpnp/windows-amd64-1.8.0_66.tar.gz
- wget https://s3-us-west-2.amazonaws.com/openpnp/windows-x86-1.8.0_66.tar.gz
- ./install4j6/bin/install4jc -r $TRAVIS_COMMIT -d installers -D mediaFileVersion=$TRAVIS_BRANCH OpenPnP.install4j

deploy:
  provider: s3
  access_key_id:
    secure: QzQReumydxD1NJzCrCSE5iLDONzJtAYg4VEK9yV6ySyLd92yNIaU7jBayGjv0936Ufsbq0xG/wpyrPoUhC0IJ9zzNiXJ7biZtFH2T2PlWN2j9MsrZJF7XOyx028IMlUSkTg0VvjewwYDbf35tAUgzwZAC2eWWtkZ44PEaCbRX3A=
  secret_access_key:
    secure: C4e7rAxiTBUQhDiZ5zs0FyzTNtRD+f+egrxhB3TBFi8jImEKbQ8hCr84TmSc0rR/ZdPEkjG0Z1gX/x1fKjrBI2tf2D6CyYjCYt9ZaHnMH0AL31yZ5H8FRyxSGM6uFjgHLbNXqaAvg2sNlPVUT4mfEmcJ+mDF1Yp/Jli+532g2Lc=
  skip_cleanup: true
  bucket: openpnp
  region: us-west-2
  local_dir: installers
  on:
    jdk: oraclejdk8
    branch:
    - develop
    - master

         